apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
    # matchExpressions:
    #   - {key: app, operator: In, values:[second-app, backend]}
  template:
    metadata:
      labels:
        app: my-app
        tier: backend
    spec:
      containers:
        - name: my-node-container
          image: amirjfr/kube-first-app
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: / # this is by default; you cna change it
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 5
        # - name: ...
        #   image:
