apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
        tier: backend
    spec:
      containers:
        - name: my-node-container
          image: amirjfr/kube-first-app
        # - name: ...
        #   image:
